# Generated by Django 3.0.8 on 2021-08-16 06:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('employees_menu', '0002_employee_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lunch',
            options={'ordering': ['name']},
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('lunchs', models.ManyToManyField(to='employees_menu.Lunch')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
