# Generated by Django 3.0.8 on 2021-08-16 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees_menu', '0004_auto_20210816_0759'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={},
        ),
        migrations.RemoveField(
            model_name='menu',
            name='name',
        ),
    ]
