# Generated by Django 3.0.8 on 2021-08-17 21:18

from django.db import migrations, models
import employees_menu.validators


class Migration(migrations.Migration):

    dependencies = [
        ('employees_menu', '0005_auto_20210816_0814'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(auto_now_add=True, validators=[employees_menu.validators.validate_create_order_before_to_11am]),
        ),
    ]
