# Generated by Django 3.0.8 on 2021-08-18 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees_menu', '0006_auto_20210817_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
